# Site settings
title: Vienna RSS
description: The Free and Open Source RSS/Atom Reader for Mac OS X
baseurl: "viennarss.github.io/" # the subpath of your site, e.g. /blog/
url: "https://viennarss.github.io" # the base hostname & protocol for your site
twitter_username: ViennaRSS
github_username:  ViennaRSS

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
